server.port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver 
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/daniels 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties.hibernate:
      format_sql: true
      show_sql: ${SHOW_SQL:true}
